package com.hiringplatform.auth_service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a user account in the system.
 * Stored in the "users" collection in MongoDB.
 */
@Document(collection = "users")
public class User {

    @Id
    private String id; // Unique identifier generated by MongoDB.

    private String username; // User's chosen login name. Must be unique.

    private String password; // Hashed password for security.

    private String role; // User's role (e.g., "RECRUITER", "JOB_SEEKER"). Determines permissions.

    private String email; // User's contact email address.

    // --- Standard Getters and Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

     public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
